.TH APG "7" "October 2021" "Andrew Gwozdziewycz" "People"
.SH NAME
apg \- Andrew Gwozdziewycz
.SH SYNOPSIS
.B github: 
https://github.com/apg
.br
.B twitter:
https://twitter.com/apgwoz
.SH DESCRIPTION    
Andrew is a software engineer at HashiCorp, primarily focused on running Vault in the cloud. 
.PP
Over the years he has contributed to a number of free and open source software projects and has told a large number of dad jokes, and bad puns.

.SH CONFORMING TO
Veganism, Drug and Alcohol Free lifestyle
.SH NOTES
Spoke at [Racket Con 2017](http://con.racket-lang.org) about [slideshow/simple](https://github.com/apg/slideshow-simple).
.PP
Appeared on [Software Engineering Daily](https://softwareengineeringdaily.com/2017/02/28/heroku-autoscaling-with-andrew-gwozdziewycz/) discussing Heroku's metrics pipeline and autoscaling.
.PP
Occassionally writes a newsletter, [hifi by apg](http://hifibyapg.com), to inspire hackers.
.PP
With the help of [James Dennis](http://jmsdnns.com), Andrew started [Hack && Tell](http://hackandtell.org) in NYC and co-organized it from 2010--2015.
.PP
With resources generously donate by Meetup, he and Nathan Hamblen organized an Occupy Together Hackathon in NYC. As a result, he appeared on the [Brian Leher Show](https://vimeo.com/31913208), and was quoted in [Mashable](http://mashable.com/2011/10/14/occupy-wall-street-hackathons/), [Huffington Post](https://secure.huffingtonpost.com/2011/10/26/occupy-wall-street-a-diy-tech-tools-protest_n_1032518.html), [Talking Points Memo](http://idealab.talkingpointsmemo.com/2011/10/hackathons-birth-new-tools-for-occupy-movement.php), and [Digits at the Wall St Journal](https://web.archive.org/web/20111116012021/http://blogs.wsj.com/digits/2011/10/14/techies-unite-for-occupy-wall-street-hackathon).
.PP
Andrew has spoken at [Racket Con 2017](http://con.racket-lang.org), [Dreamforce](https://dreamforce.com), [SD Devops](https://github.com/sddevops/presentations/tree/gh-pages/shard-your-shelf), [Lambdaconf 2016](https://www.youtube.com/watch?v=RuUrMqkASUU), the first [!!Con](https://www.youtube.com/watch?v=QLzhB6c8uCg), too many Hack && Tells to count, as well as Braindump NYC, [NYC Python](https://www.meetup.com/nycpython/), and Django NYC.
.PP
He was interviewed for [We Are NY Tech](http://wearenytech.com/32-andrew-gwozdziewycz-software-engineer-at-meetup) in 2010.
.PP
Years ago, he interviewed a number of tech organizers for [Congregating.us]().
.SH BUGS
Starts projects, doesn't fini
.SH SEE ALSO
[SIGUSR2](http://sigusr2.net), [bsd.network](https://bsd.network/@apg), [Gitlab](https://gitlab.com/apg), [GitHub](https://github.com/apg), [Twitter](https://twitter.com/apgwoz), [Flickr](https://flickr.com/photos/thinkiandy)
